package:
  name: s3proxy
  version: 2.0.0
  epoch: 0
  description: "Access other storage backends via the S3 API"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: ''
      license: 'Apache License 2.0'
  dependencies:
    runtime:
      - openjdk-11

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - maven
      - openjdk-11

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sourcegraph/s3proxy/archive/refs/tags/s3proxy-${{package.version}}.tar.gz
      expected-sha256: e2d3f8f217d67ab8cc074490f27b4d649f4ec73f5bf540aa9da1ad4dda818d0b
      extract: true
  - runs: |
      mvn package -DskipTests
      ls -al target/
  - runs: |
      mkdir -p ${{targets.destdir}}/opt/s3proxy/
      cp target/* ${{targets.destdir}}/opt/s3proxy/
      cp src/main/resources/run-docker-container.sh ${{targets.destdir}}/opt/s3proxy
